//admin actions
export const EDIT_USER = 'ADMIN/EDIT_USER';
export const DELETE_USER = 'ADMIN/DELETE_USER';
export const GET_USER = 'ADMIN/GET_USER';
export const FETCH_ALL_USER = 'ADMIN/FETCH_ALL_USER';
export const SHOW_USER_DETAIL = 'ADMIN/SHOW_USER_DETAIL';
export const SORT_USER = 'ADMIN/SORT_USER';
export const FILTER_USER = 'ADMIN/FILTER_USER';

//cart actions
export const ADD_MOVIE_TO_CART = 'CART/ADD_MOVIE_TO_CART';
export const REMOVE_MOVIE_FROM_CART = 'CART/REMOVE_MOVIE_FROM_CART';
export const MINUS_MOVIE_BY_ONE_FROM_CART = 'CART/MINUS_MOVIE_BY_ONE_FROM_CART';

export const PURCHASE_ITEM_IN_CART = 'CART/PURCHASE_ITEM_IN_CART';
export const UPDATE_MOVIE_CART = 'CART/UPDATE_MOVIE_CART';

//common
export const SEND_API_START = 'API/SEND_API_START';
export const SEND_API_SUCCESS = 'API/SEND_API_SUCCESS';
export const SEND_API_FAIL = 'API/SEND_API_FAIL';

//user actions
export const LOGIN_USER = 'USER/LOGIN_USER';
export const LOGOUT_USER = 'USER/LOGOUT_USER';

//collection actions
export const ADD_MOVIE_TO_COLLECTION_WHISLIST =
  'COLLECTION/ADD_MOVIE_TO_COLLECTION_WHISLIST';
export const ADD_MOVIE_TO_COLLECTION_FINISHED =
  'COLLECTION/ADD_MOVIE_TO_COLLECTION_FINISHED';
export const REMOVIE_MOVIE_FROM_COLLECTION =
  'COLLECTION/REMOVIE_MOVIE_FROM_COLLECTION';
export const TOGGLE_MOVIE_IN_COLLECTION =
  'COLLECTION/TOGGLE_MOVIE_IN_COLLECTION';
export const UPDATE_MOVIE_COLLECTION = 'COLLECTION/UPDATE_MOVIE_COLLECTION';

//movie actions
export const ALLOW_MOVIE_TO_DISPLAY = 'MOVIE/ALLOW_MOVIE_TO_DISPLAY';
export const FETCH_DISPLAYED_MOVIE_LIST = 'MOVIE/FETCH_DISPLAYED_MOVIE_LIST';
export const ADD_COMMENT_TO_MOVIE = 'MOVIE/ADD_COMMENT_TO_MOVIE';
export const GET_MOVIE_DETAIL = 'MOVIE/GET_MOVIE_DETAIL';
