export const EDIT_USER = 'ADMIN/EDIT_USER';
export const DELETE_USER = 'ADMIN/DELETE_USER';
export const GET_USER = 'ADMIN/GET_USER';
export const SET_ALL_USER = 'ADMIN/SET_ALL_USER';
export const SHOW_USER_DETAIL = 'ADMIN/SHOW_USER_DETAIL';
export const SORT_USER = 'ADMIN/SORT_USER';
export const FILTER_USER = 'ADMIN/FILTER_USER';

export const ADD_MOVIE_TO_CART = 'CART/ADD_MOVIE_TO_CART';
export const REMOVE_MOVIE_FROM_CART = 'CART/REMOVE_MOVIE_FROM_CART';
export const MINUS_MOVIE_BY_ONE_FROM_CART = 'CART/MINUS_MOVIE_BY_ONE_FROM_CART';

export const LOGIN_USER = 'USER/LOGIN_USER';
export const LOGOUT_USER = 'USER/LOGOUT_USER';
export const ADD_MOVIE_TO_COLLECTION = 'USER/ADD_MOVIE_TO_COLLECTION';
export const REMOVIE_MOVIE_FROM_COLLECTION =
  'USER/REMOVIE_MOVIE_FROM_COLLECTION';
