export const EDIT_USER = 'USER/EDIT_USER';
export const DELETE_USER = 'USER/DELETE_USER';
export const GET_USER = 'USER/GET_USER';
export const SET_ALL_USER = 'USER/SET_ALL_USER';
export const SHOW_USER_DETAIL = 'USER/SHOW_USER_DETAIL';
export const SORT_USER = 'USER/SORT_USER';
export const FILTER_USER = 'USER/FILTER_USER';

export const ADD_MOVIE_TO_CART = 'CART/ADD_MOVIE_TO_CART';
export const REMOVE_MOVIE = 'CART/REMOVE_MOVIE';
export const MINUS_MOVIE_BY_ONE = 'CART/MINUS_MOVIE_BY_ONE';
